### ISSUE TITLE
Feature: change language on demand

### ISSUE THREAD

**Issue by zaovb** [AdamGuidarini/MediTrak#105]
It would be nice to have a menu to switch languages.

**Comment by AdamGuidarini** [comment]
That would definitely be useful. In Android 12+ you can change the language by long pressing the app icon, selecting "app info" and then "app language". But having it in the app would be more convenient.

**Comment by AdamGuidarini** [comment]
Sorry it took a little while, but this is not out in version 0.12.8

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.12.8
