### ISSUE TITLE
Feature Request: allow decimals in dosage

### ISSUE THREAD

**Issue by N-Upchurch** [AdamGuidarini/MediTrak#109]
It would be nice to be able to enter ".5 mg" etc when setting up a medication.

**Comment by AdamGuidarini** [comment]
Should be doable, updating the UI at least should be simple enough there

**Comment by AdamGuidarini** [comment]
The newest release, 0.13.2 addresses this request by adding support for up to 3 decimal places in dosages.

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.13.2
