### ISSUE TITLE
v0.12.8 release has a debug APK

### ISSUE THREAD

**Issue by obfusk** [AdamGuidarini/MediTrak#112]
https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.12.8 has a debug APK attached instead of a release APK.

cc @IzzySoft

**Comment by AdamGuidarini** [comment]
Thank you for noticing! I deleted the old release and added a new one

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.12.8

**Comment by IzzySoft** [comment]
Btw, your IoD badge in the Readme links to itself instead of [to your app at IzzyOnDroid](https://apt.izzysoft.de/packages/projects.medicationtracker) :wink:

**Comment by AdamGuidarini** [comment]
> Btw, your IoD badge in the Readme links to itself instead of [to your app at IzzyOnDroid](https://apt.izzysoft.de/packages/projects.medicationtracker) 😉

Thanks for letting me know! Just fixed it. Just needed to wrap the <img> tags with <a href="...">

**Comment by IzzySoft** [comment]
I don't know with what, but it worked :smile: thanks!
