### ISSUE TITLE
Feature request: "Take All"

### ISSUE THREAD

**Issue by linker3000** [AdamGuidarini/MediTrak#115]
For multiple meds to be taken at the same time, it would be good to have a group "Take all" feature instead of having to tick them individually.

Thanks.

**Comment by AdamGuidarini** [comment]
Hello! What are you thinking for this? For me, a 3rd button with in notifications with a "Take All" Label comes to mind, is that what you were thinking of as well? Or were you thinking of something that would display in the app's schedule, like a button below the checkboxes for medications taken at the same time?

**Comment by linker3000** [comment]
Hi, it's the alerts on my Android phone - the ones you see when you pull the screen down - see image. Instead of multiple alerts, can there be on for all meds to be taken at the same time, with a 'take all' option and a link to go to the app if you need to mark meds selectively.

This functionality would be identical to another (commercial) app I want to remove.

Thanks

![Screenshot_20240823-132635](https://github.com/user-attachments/assets/908b4b11-067d-4cf8-acc6-a3ac5f8cb988)

**Comment by AdamGuidarini** [comment]
I have a couple ideas of how to implement something like that, but I'm not sure if they're all possible. I could set it up so it displays a single notification if you have more than 5 (for example) notifications with the "Take all" and "snooze" buttons. I might also add a dialog that opens up when you have pending notifications asking which you like to take (with a take all option)

**Comment by linker3000** [comment]
That sounds like it will make things easier. Thanks.

**Comment by AdamGuidarini** [comment]
Hello! It took some time to implement, but these changes are part of the latest release!

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.13.0
