### ISSUE TITLE
Adding a non-integer as a dosage causes app to crash

### ISSUE THREAD

**Issue by avipars** [AdamGuidarini/MediTrak#132]
My Samsung keyboard has a decimal (and comma) option in the numpad. Entering the decimal point causes the app to crash.

I tried this with the intention to add a dose as a float/double (e.g. half a pill or 15.5 mg)

**Comment by avipars** [comment]
I'll try to make a pull request if I have the chance

**Comment by avipars** [comment]
issue only occurs when I type in a "." as the first character

**Comment by AdamGuidarini** [comment]
Thank you! The PR looks good, I should have a chance to run and test it tomorrow, Friday, or Saturday and then merge it.

**Comment by AdamGuidarini** [comment]
Just release version 0.13.4 with this fix. Thank you for finding this and for your help fixing it!
