### ISSUE TITLE
Trying to view history of As Needed medications causes app freeze and black screen

### ISSUE THREAD

**Issue by remerus** [AdamGuidarini/MediTrak#138]
When trying to view the history of a non-scheduled medication, the app freezes, then shows a black screen.  Only way out is to force-close the app.

Viewing the history of a medication with a schedule/frequency works every time.

Steps to reproduce:
* Add a new medication, set Frequency to  "As Needed"
* Go to My Medications, tap on "History"
* App crash

Can always reproduce, does not matter if medication has doses or not. 
Start date setting does not seem to change the behaviour.

Environment: 
Samsung Galaxy S9, Android 10, kernel version 4.9.118-23733677 (21-07-2022, 10:29:10 KST)

**Comment by AdamGuidarini** [comment]
Thanks for letting me know! I should have time to take a look at it this week. I'm guessing it's related to searching for a scheduled time which an as needed dose wouldn't have, but I thought I set it up to handle that

**Comment by AdamGuidarini** [comment]
Just released version 0.13.5 with the fix for this:

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.13.5
