### ISSUE TITLE
Are some Screenshots available?

### ISSUE THREAD

**Issue by IzzySoft** [AdamGuidarini/MediTrak#47]
I've just integrated your app [with my repo](https://apt.izzysoft.de/packages/projects.medicationtracker/), where it will become visible with the next sync in about an hour. This can help your (potential) testers who have no access to Google Play. APKs in my repo are fetched from your (pre-)releases within 24h of your making them available at a new release tag.

To raise interest, it would be nice if the listing could include some screenshots. Would you have such available for "public viewing"? Thanks in advance!

**Comment by AdamGuidarini** [comment]
Hello, thank you for reaching out! I've attached a couple screenshots to this comment. Let me know if there's anything else I can do to help! I'll probably have a new release ready with styling changes, bug fixes, and some UX improvements. Will your repo fetch the newest updates from my releases as well?

- Adam

![Screenshot_20231217_123444](https://github.com/AdamGuidarini/MediTrak/assets/45023561/7c60341c-d381-4cfe-9766-9906847e12ac)
![Screenshot_20231217_123527](https://github.com/AdamGuidarini/MediTrak/assets/45023561/0d6c24ce-6fc2-464c-9a1a-6ade89156335)
![Screenshot_20231217_123738](https://github.com/AdamGuidarini/MediTrak/assets/45023561/19fc9b0b-ac86-442c-9f2a-6e32edad40ec)
![Screenshot_20231217_124751](https://github.com/AdamGuidarini/MediTrak/assets/45023561/0cca4333-cc54-40f0-a717-89eb17c7842c)

**Comment by IzzySoft** [comment]
> Hello, thank you for reaching out! I've attached a couple screenshots to this comment.

Thanks a lot! I've just fetched them and integrated them here, they will show up with the next sync around 7 pm UTC.

> Let me know if there's anything else I can do to help!

I could offer you a PR with the metadata set up here, using Fastlane structures. This would enable you to adjust whenever and whatever you feel needed (and who should know that better than you), and also maybe add per-release changelogs or a featureGraphic if you like. You're welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance with that. If that sounds good to you and you want me to open that PR, just let me know!

Oh, btw, those very same Fastlane data could be used for your future deployments to PlayStore, you'd just need to add and configure the Fastlane binaries for that (they are not needed for my repo).

> I'll probably have a new release ready with styling changes, bug fixes, and some UX improvements. Will your repo fetch the newest updates from my releases as well?

Yes, as pointed out in my initial comment:

> APKs in my repo are fetched from your (pre-)releases within 24h of your making them available at a new release tag.

So whenever you make a new release (and have the `versionCode` increased properly), tagged it, and attached the APK – between 6 pm and 7 pm UTC my update checker will fetch it.

**Comment by AdamGuidarini** [comment]
That be great if you could put up that PR! Would you be able branch off of/merge into the vc11 branch? That's the branch that will merge into main for my next release.

**Comment by IzzySoft** [comment]
I can try. Usually I just pick whatever is the default branch when forking. […] Ah, OK, managed that: `git clone <url> --banch vc11`, good. OK, give me a minute or two, PR is on its way…
