### ISSUE TITLE
Notification timer

### ISSUE THREAD

**Issue by Zaxx69** [AdamGuidarini/MediTrak#48]
Please provide a feature which can help us set time limits for medications ,for example doctor prescribed meds for morning ,evening ,night before food or after food .sometime it's not possible to remember the right time to take our meds .so if we can set custom notifications for each med ,it will be very helpful

Thank you for this app

**Comment by AdamGuidarini** [comment]
Hello! That's a good idea! I'll add it to my to-do list and leave this issue open until I finish it.

**Comment by Zaxx69** [comment]
Thank you

**Comment by AdamGuidarini** [comment]
Hello, I think I've added these changes , but let me know if there's anything else to add :) (Or if there's part of this request I didn't catch)
