### ISSUE TITLE
Translatable

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [AdamGuidarini/MediTrak#49]
Is this app Translatable ?

**Comment by AdamGuidarini** [comment]
Unfortunately only English is currently supported, I do plan on adding Spanish and Italian on my own as well as trying out machine translators (Reverso, Google Translate, ChatGPT) for additional languages

**Comment by AdamGuidarini** [comment]
Hello, I was looking back through opened issues and realized I may have miss understood you originally. The app is translatable in the sense that all the text displayed to users is stores as string resources, how ever when I first answered English was the only language. A pull request was recently raised that contained German translations which I have merged into the branch storing changes for the next release.

The English string resources can be found here:

https://github.com/AdamGuidarini/MediTrak/blob/main/app/src/main/res/values/strings.xml

And there German ones are currently located here:

https://github.com/AdamGuidarini/MediTrak/blob/vc16/app/src/main/res/values-de/strings.xml
