### ISSUE TITLE
'+' floating button to add a medication or a new user quickly

### ISSUE THREAD

**Issue by serrq** [AdamGuidarini/MediTrak#55]
It would be more fast add a new medication through a floating button. In my opinion.

**Comment by AdamGuidarini** [comment]
I took a bit of a different route inspired by this request. I tried out the floating button, but I ended up opting for a "+" button in the bar on top next to the 3 dot button since the floating button conflicted with the "i" buttons for some doses. This change is in the latest release v0.12.0
