### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [AdamGuidarini/MediTrak#56]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, EPIC, FTM, XRP, XDC, ADA, XLM, XMR addresses available for donations (addresses have to be copyable).

Here an integration example made by other developers.

![1000092943](https://github.com/AdamGuidarini/MediTrak/assets/113377431/528e3065-97e2-4851-a590-ecaece5e2727)

**Comment by AdamGuidarini** [comment]
I'm truly flattered that you would like to provide donations to the project. However, at the moment I feel that I already have all the materials I need for development. Instead, I ask that donations be redirected to charities like [Doctor's Without Borders](https://www.doctorswithoutborders.org/get-involved/ways-to-give) that help people in need.
