### ISSUE TITLE
If I forget to add the date, the new medication is not saved

### ISSUE THREAD

**Issue by serrq** [AdamGuidarini/MediTrak#57]

**Comment by AdamGuidarini** [comment]
I did some testing so far it looks like if you set up a medication so it's valid and then change to another frequency, for example daily to as needed, it won't flip the frequency back to invalid. I'll do some more investigating, but all frequency fields are meant to be required.

**Comment by AdamGuidarini** [comment]
This bug is fixed as over the newest release (v0.11.1).
