### ISSUE TITLE
Group notifications together

### ISSUE THREAD

**Issue by Kreuger** [AdamGuidarini/MediTrak#65]
Hello. I was wondering if you could add the option to group notifications together so that I dont have one for each medication.

**Comment by AdamGuidarini** [comment]
This would be a very good change to make, thank you for the suggestion! I've added this to my to-do list.

**Comment by Kreuger** [comment]
Great. Thank you!

**Comment by AdamGuidarini** [comment]
I'm happy to say that as of the latest release (v0.12.0) notifications are now grouped together!
