### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by TheBiostarfly** [AdamGuidarini/MediTrak#69]
Hello,

When tapping on the notification the app doesn't always open. I've tried to find a pattern in that behavior and I think it happens when there are muliple notifications for different medications. 

And also I think it would be helpful if notifications would be repushed when the medication hasn't been taken yet, e.g. I rebooted my phone the notification is gone and won't be shown again until the next schedule time or when you swipe the notification away. 

Thank you for your work I enyoj using your app!

**Comment by AdamGuidarini** [comment]
Reposting notifications is definitely something I want added in. I haven't noticed the issue with the app not opening, but I can investigate it. I usually just mark as taken through the notification though so that could be how I missed it.

**Comment by AdamGuidarini** [comment]
Hello! I think this bug is fixed and the latest release [0.13.0](https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.13.0) adds retriggering  notifications that were present before a reboot or force stopping and rebooting the app
