### ISSUE TITLE
Changing time and date format

### ISSUE THREAD

**Issue by TheBiostarfly** [AdamGuidarini/MediTrak#97]
When I reinstalled the app I had to change the time and date format and noticed when I tried changing both the same time only the latter got saved. 

When I changed the date or time format separately, the change got saved. 

Just a minor bug I guess, but can be confusing.

**Comment by AdamGuidarini** [comment]
Good catch. Think commit has a fix for it

https://github.com/AdamGuidarini/MediTrak/commit/49b15ee061b38d695072b6ad18504c8c10b039a2

I'm still trying to solve that notifications issue, I'll release this when I have a fix for that as well

**Comment by AdamGuidarini** [comment]
Fixed in version 0.12.4
